name: Clang-format Verification
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  format-checking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '13'
          check-path: 'Source'
